### PR TITLE
Polished for FCMRebooted Demo

### PR DESCRIPTION
**Pull request by Ztaclie**
### Summary
This pull request refines the README for the FCM Rebooted Demo project, making it more user-friendly and professional.

### Key Changes
- Structured content with clear and consistent headings.
- Added code blocks for configuration paths, commands, and JSON examples.
- Streamlined language for readability and simplicity.
- Highlighted key warnings and notes for better visibility.
- Enhanced navigation with cross-referenced links.

### Benefits
- Easier for developers to follow configuration and setup instructions.
- Improved clarity and usability for the README.
- Better alignment with professional documentation standards.

Please review and suggest any additional improvements!

### CODE REVIEW

**Comment by DelphiWorlds** [comment]
On line 8, it should read: "multiple lines of text", as per the original
On line 11, it should read: "You no longer need to create any classes.." (not sure why you used the word "custom"?) 
Lines 167 onwards seem to be included by mistake?

The section regarding the manifest is going to need some refinement, since the changes in 12.1 have broken the manifest merge that worked up until 12.0. It will need to advise users of 12.1 or later to make the changes that would have occurred if the merge worked.

**Comment by Ztaclie** [comment]
Hi ,

I have made the changes as per your feedback:

1. Updated line 8 to read "multiple lines of text.
2. "Replaced "custom" with "any" on line 11.
3. Removed the unintended lines from 167 onwards.
4. Refined the Android manifest section to address the changes required for Delphi 12.1 or later, including a note on manually applying the changes due to the broken manifest merge.

Please let me know if there are any additional adjustments needed. Thank you for your review and guidance!

**Comment by DelphiWorlds** [comment]
It seems the unintended lines are still there?
https://github.com/DelphiWorlds/Kastri/tree/aebcaa309d1919decfe965f6f3b938c61746897d/Demos/FCMRebooted

**Comment by DelphiWorlds** [comment]
Thanks!

**Pull request merged**
